universe = vanilla
executable = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/JobRun/run_bilby.sh
notification = error
accounting_group = ligo.dev.o3.burst.paramest.bayeswave
RequestMemory = 4000
RequestCpus = 1
log = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/JobRun/Logs/run_bilby.log
output = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/JobRun/Logs/run_bilby.out
error = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/JobRun/Logs/run_bilby.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue 1

