universe = vanilla
executable = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/Surrogate_FramesSearch/run_bilby.sh
notification = error
accounting_group = ligo.dev.o3.burst.paramest.bayeswave
RequestMemory = 4000
RequestCpus = 12
log = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/Surrogate_FramesSearch/Logs/run_bilby.log
output = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/Surrogate_FramesSearch/Logs/run_bilby.out
error = /home/maria.okounkova/BeyondGRAnalysis/BilbyPE/Surrogate_FramesSearch/Logs/run_bilby.err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue 1

